### ISSUE TITLE
Can't find library on Maven

### ISSUE THREAD

**Issue by jkcailteux** [dvoiss/android-geocities-theme#1]
What repository do we need to add to pull this in via gradle?

`compile 'com.github.dvoiss:android-geocities-theme:0.1.0'` doesn't work even on a brand new project.

**Comment by dvoiss** [comment]
Hi @jkcailteux, it was on jitpack but jitpack wasn't able to build it properly. It's now being uploaded to jcenter. Syncing with jcenter apparently takes some time however, so I'll update this issue when it's available.

**Comment by dvoiss** [comment]
@jkcailteux resolved the issue w/ jitpack. It's now available. 👍

**Comment by jkcailteux** [comment]
Awesome, thanks for doing that. Can't wait to geocities out my app.
