### ISSUE TITLE
Error:Failed to resolve: pl.droidsonroids.gif:android-gif-drawable:1.2.9-SNAPSHOT

### ISSUE THREAD

**Issue by jkcailteux** [dvoiss/android-geocities-theme#2]
Can't get a sample app to build, with this error.

**Comment by jkcailteux** [comment]
Fixed by adding:     
`maven { url "https://oss.sonatype.org/content/repositories/snapshots" }`

**Comment by dvoiss** [comment]
Fixed, thanks for letting me know 👍
